//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSBIDE.Library.ServiceClient.OsbideWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OsbideUser", Namespace="http://schemas.datacontract.org/2004/07/OSBIDE.Library.Models")]
    [System.SerializableAttribute()]
    public partial class OsbideUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _firstNameField;
        
        private string _institutionIdField;
        
        private string _lastNameField;
        
        private int Idk__BackingFieldField;
        
        private int OsbleIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _firstName {
            get {
                return this._firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this._firstNameField, value) != true)) {
                    this._firstNameField = value;
                    this.RaisePropertyChanged("_firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _institutionId {
            get {
                return this._institutionIdField;
            }
            set {
                if ((object.ReferenceEquals(this._institutionIdField, value) != true)) {
                    this._institutionIdField = value;
                    this.RaisePropertyChanged("_institutionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _lastName {
            get {
                return this._lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this._lastNameField, value) != true)) {
                    this._lastNameField = value;
                    this.RaisePropertyChanged("_lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OsbleId>k__BackingField", IsRequired=true)]
        public int OsbleIdk__BackingField {
            get {
                return this.OsbleIdk__BackingFieldField;
            }
            set {
                if ((this.OsbleIdk__BackingFieldField.Equals(value) != true)) {
                    this.OsbleIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("OsbleIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLog", Namespace="http://schemas.datacontract.org/2004/07/OSBIDE.Library.Models")]
    [System.SerializableAttribute()]
    public partial class EventLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateReceived {
            get {
                return this.DateReceivedField;
            }
            set {
                if ((this.DateReceivedField.Equals(value) != true)) {
                    this.DateReceivedField = value;
                    this.RaisePropertyChanged("DateReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogType {
            get {
                return this.LogTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTypeField, value) != true)) {
                    this.LogTypeField = value;
                    this.RaisePropertyChanged("LogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="OsbideWebService.OsbideWebService")]
    public interface OsbideWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/Echo", ReplyAction="urn:OsbideWebService/EchoResponse")]
        string Echo(string toEcho);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetUserById", ReplyAction="urn:OsbideWebService/GetUserByIdResponse")]
        OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/SaveUser", ReplyAction="urn:OsbideWebService/SaveUserResponse")]
        OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser SaveUser(OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser userToSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/SubmitLog", ReplyAction="urn:OsbideWebService/SubmitLogResponse")]
        int SubmitLog(OSBIDE.Library.ServiceClient.OsbideWebService.EventLog log);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetPastEvents", ReplyAction="urn:OsbideWebService/GetPastEventsResponse")]
        OSBIDE.Library.ServiceClient.OsbideWebService.EventLog[] GetPastEvents(System.DateTime start, bool waitForContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetUsers", ReplyAction="urn:OsbideWebService/GetUsersResponse")]
        OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser[] GetUsers(int[] osbideIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/LibraryVersionNumber", ReplyAction="urn:OsbideWebService/LibraryVersionNumberResponse")]
        string LibraryVersionNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/OsbidePackageUrl", ReplyAction="urn:OsbideWebService/OsbidePackageUrlResponse")]
        string OsbidePackageUrl();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OsbideWebServiceChannel : OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OsbideWebServiceClient : System.ServiceModel.ClientBase<OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService>, OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService {
        
        public OsbideWebServiceClient() {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OsbideWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string toEcho) {
            return base.Channel.Echo(toEcho);
        }
        
        public OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser SaveUser(OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser userToSave) {
            return base.Channel.SaveUser(userToSave);
        }
        
        public int SubmitLog(OSBIDE.Library.ServiceClient.OsbideWebService.EventLog log) {
            return base.Channel.SubmitLog(log);
        }
        
        public OSBIDE.Library.ServiceClient.OsbideWebService.EventLog[] GetPastEvents(System.DateTime start, bool waitForContent) {
            return base.Channel.GetPastEvents(start, waitForContent);
        }
        
        public OSBIDE.Library.ServiceClient.OsbideWebService.OsbideUser[] GetUsers(int[] osbideIds) {
            return base.Channel.GetUsers(osbideIds);
        }
        
        public string LibraryVersionNumber() {
            return base.Channel.LibraryVersionNumber();
        }
        
        public string OsbidePackageUrl() {
            return base.Channel.OsbidePackageUrl();
        }
    }
}
