//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSBIDE.Library.ServiceClient.OsbideWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="OsbideWebService.OsbideWebService")]
    public interface OsbideWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/Echo", ReplyAction="urn:OsbideWebService/EchoResponse")]
        string Echo(string toEcho);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetUserById", ReplyAction="urn:OsbideWebService/GetUserByIdResponse")]
        OSBIDE.Library.Models.OsbideUser GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/SaveUser", ReplyAction="urn:OsbideWebService/SaveUserResponse")]
        OSBIDE.Library.Models.OsbideUser SaveUser(OSBIDE.Library.Models.OsbideUser userToSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/SubmitLog", ReplyAction="urn:OsbideWebService/SubmitLogResponse")]
        int SubmitLog(OSBIDE.Library.Models.EventLog log);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetPastEvents", ReplyAction="urn:OsbideWebService/GetPastEventsResponse")]
        OSBIDE.Library.Models.EventLog[] GetPastEvents(System.DateTime start, bool waitForContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/GetUsers", ReplyAction="urn:OsbideWebService/GetUsersResponse")]
        OSBIDE.Library.Models.OsbideUser[] GetUsers(int[] osbideIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/LibraryVersionNumber", ReplyAction="urn:OsbideWebService/LibraryVersionNumberResponse")]
        string LibraryVersionNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OsbideWebService/OsbidePackageUrl", ReplyAction="urn:OsbideWebService/OsbidePackageUrlResponse")]
        string OsbidePackageUrl();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OsbideWebServiceChannel : OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OsbideWebServiceClient : System.ServiceModel.ClientBase<OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService>, OSBIDE.Library.ServiceClient.OsbideWebService.OsbideWebService {
        
        public OsbideWebServiceClient() {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OsbideWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OsbideWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string toEcho) {
            return base.Channel.Echo(toEcho);
        }
        
        public OSBIDE.Library.Models.OsbideUser GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public OSBIDE.Library.Models.OsbideUser SaveUser(OSBIDE.Library.Models.OsbideUser userToSave) {
            return base.Channel.SaveUser(userToSave);
        }
        
        public int SubmitLog(OSBIDE.Library.Models.EventLog log) {
            return base.Channel.SubmitLog(log);
        }
        
        public OSBIDE.Library.Models.EventLog[] GetPastEvents(System.DateTime start, bool waitForContent) {
            return base.Channel.GetPastEvents(start, waitForContent);
        }
        
        public OSBIDE.Library.Models.OsbideUser[] GetUsers(int[] osbideIds) {
            return base.Channel.GetUsers(osbideIds);
        }
        
        public string LibraryVersionNumber() {
            return base.Channel.LibraryVersionNumber();
        }
        
        public string OsbidePackageUrl() {
            return base.Channel.OsbidePackageUrl();
        }
    }
}
