//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSBIDE.Data.SQLDatabase.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OsbideProcs : DbContext
    {
        public OsbideProcs()
            : base("name=OsbideProcs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetEventLogs_Result> GetActivityFeeds(Nullable<System.DateTime> dateReceivedMin, Nullable<System.DateTime> dateReceivedMax, string eventLogIds, string eventTypes, Nullable<int> courseId, Nullable<int> roleId, string senderIds, Nullable<int> minLogId, Nullable<int> maxLogId, Nullable<int> offsetN, Nullable<int> topN)
        {
            var dateReceivedMinParameter = dateReceivedMin.HasValue ?
                new ObjectParameter("DateReceivedMin", dateReceivedMin) :
                new ObjectParameter("DateReceivedMin", typeof(System.DateTime));
    
            var dateReceivedMaxParameter = dateReceivedMax.HasValue ?
                new ObjectParameter("DateReceivedMax", dateReceivedMax) :
                new ObjectParameter("DateReceivedMax", typeof(System.DateTime));
    
            var eventLogIdsParameter = eventLogIds != null ?
                new ObjectParameter("EventLogIds", eventLogIds) :
                new ObjectParameter("EventLogIds", typeof(string));
    
            var eventTypesParameter = eventTypes != null ?
                new ObjectParameter("EventTypes", eventTypes) :
                new ObjectParameter("EventTypes", typeof(string));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var senderIdsParameter = senderIds != null ?
                new ObjectParameter("SenderIds", senderIds) :
                new ObjectParameter("SenderIds", typeof(string));
    
            var minLogIdParameter = minLogId.HasValue ?
                new ObjectParameter("MinLogId", minLogId) :
                new ObjectParameter("MinLogId", typeof(int));
    
            var maxLogIdParameter = maxLogId.HasValue ?
                new ObjectParameter("MaxLogId", maxLogId) :
                new ObjectParameter("MaxLogId", typeof(int));
    
            var offsetNParameter = offsetN.HasValue ?
                new ObjectParameter("OffsetN", offsetN) :
                new ObjectParameter("OffsetN", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventLogs_Result>("GetActivityFeeds", dateReceivedMinParameter, dateReceivedMaxParameter, eventLogIdsParameter, eventTypesParameter, courseIdParameter, roleIdParameter, senderIdsParameter, minLogIdParameter, maxLogIdParameter, offsetNParameter, topNParameter);
        }
    
        public virtual ObjectResult<GetRecentCompileErrors_Result> GetRecentCompileErrors(Nullable<int> senderId, Nullable<System.DateTime> timeframe)
        {
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(int));
    
            var timeframeParameter = timeframe.HasValue ?
                new ObjectParameter("Timeframe", timeframe) :
                new ObjectParameter("Timeframe", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentCompileErrors_Result>("GetRecentCompileErrors", senderIdParameter, timeframeParameter);
        }
    
        public virtual ObjectResult<GetComments_Result> GetComments(string eventLogIds, Nullable<int> currentUserId)
        {
            var eventLogIdsParameter = eventLogIds != null ?
                new ObjectParameter("EventLogIds", eventLogIds) :
                new ObjectParameter("EventLogIds", typeof(string));
    
            var currentUserIdParameter = currentUserId.HasValue ?
                new ObjectParameter("CurrentUserId", currentUserId) :
                new ObjectParameter("CurrentUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetComments_Result>("GetComments", eventLogIdsParameter, currentUserIdParameter);
        }
    
        public virtual ObjectResult<GetProcedureData_Result> GetProcedureData(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string nameToken, Nullable<int> gender, Nullable<int> ageFrom, Nullable<int> ageTo, Nullable<int> courseId, Nullable<int> courseYear, Nullable<decimal> gradeFrom, Nullable<decimal> gradeTo, Nullable<decimal> overallGradeFrom, Nullable<decimal> overallGradeTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var nameTokenParameter = nameToken != null ?
                new ObjectParameter("nameToken", nameToken) :
                new ObjectParameter("nameToken", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(int));
    
            var ageFromParameter = ageFrom.HasValue ?
                new ObjectParameter("ageFrom", ageFrom) :
                new ObjectParameter("ageFrom", typeof(int));
    
            var ageToParameter = ageTo.HasValue ?
                new ObjectParameter("ageTo", ageTo) :
                new ObjectParameter("ageTo", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var courseYearParameter = courseYear.HasValue ?
                new ObjectParameter("courseYear", courseYear) :
                new ObjectParameter("courseYear", typeof(int));
    
            var gradeFromParameter = gradeFrom.HasValue ?
                new ObjectParameter("gradeFrom", gradeFrom) :
                new ObjectParameter("gradeFrom", typeof(decimal));
    
            var gradeToParameter = gradeTo.HasValue ?
                new ObjectParameter("gradeTo", gradeTo) :
                new ObjectParameter("gradeTo", typeof(decimal));
    
            var overallGradeFromParameter = overallGradeFrom.HasValue ?
                new ObjectParameter("overallGradeFrom", overallGradeFrom) :
                new ObjectParameter("overallGradeFrom", typeof(decimal));
    
            var overallGradeToParameter = overallGradeTo.HasValue ?
                new ObjectParameter("overallGradeTo", overallGradeTo) :
                new ObjectParameter("overallGradeTo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProcedureData_Result>("GetProcedureData", dateFromParameter, dateToParameter, nameTokenParameter, genderParameter, ageFromParameter, ageToParameter, courseIdParameter, courseYearParameter, gradeFromParameter, gradeToParameter, overallGradeFromParameter, overallGradeToParameter);
        }
    }
}
